[package]
name = "macroassembler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
tinyvec = { version = "1.6", features = ["alloc"] }
libc = "0.2"
capstone = "0.11"
parking_lot = "0.12"
once_cell = "1.17"
num-traits = "0.2"
errno = "0.3"